FROM python:3.10

WORKDIR /app

COPY requirements.txt ./requirements.txt
COPY . .

RUN pip install --no-cache-dir -r requirements.txt

CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "5000"]
